version: '3.8'
services:
  bot:
    build: .
    stop_grace_period: 30s  # Fixed: underscore instead of hyphen
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_RECIPIENT=${EMAIL_RECIPIENT}
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    #restart: unless-stopped  # Uncommented (recommended for production)
    # Optional but recommended additions:
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f telegram_bot.py || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
